AppBundle\Entity\Project:
    type: entity
    table: project
    indexes:
        fk_project_workspace_idx:
            columns:
                - workspace_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 255
            options:
                fixed: false
        dueDate:
            type: datetime
            nullable: true
            column: due_date
    manyToOne:
        workspace:
            targetEntity: Workspace
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                workspace_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
